name: Generate JavaDoc
on: [ push ]

jobs:
  publish-and-doc:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.head_commit.message,'[javadoc]') &&
      github.repository == 'PlumyGame/mgpp'
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build dokka doc
        run: |
          chmod +x gradlew
          ./gradlew :main:dokkaHtml

      - name: Update document
        run: |
          cd ../
          git clone --depth 1 https://github.com/PlumyGame/mgppDoc.git
          cp -r ./mgpp/main/build/dokka/html/* ./mgppDoc
          cd mgppDoc
          git add .
          git config --global user.email "Li_plum@outlook.com"
          git config --global user.name "liplum"
          git commit --allow-empty -m "${{ github.event.head_commit.message }}"
          git push https://Liplum:${{ secrets.API_TOKEN_GITHUB }}@github.com/PlumyGame/mgppDoc

